#!/bin/bash

# $2 is the install location, which is ~/Applications/Cantera by default
PREFIX=$2

# This directory should be created when MATLAB is installed
MATLAB_STARTUP="${HOME}/Documents/MATLAB/startup.m"

if [ -f "${MATLAB_STARTUP}" ]; then
    sed -i '.cantera.bak' '/.* % added by Cantera installer$/d' "${MATLAB_STARTUP}"
fi

echo "
addpath(genpath('${PREFIX}/matlab')) % added by Cantera installer
setenv('CANTERA_DATA', '${PREFIX}/data') % added by Cantera installer" >> "${MATLAB_STARTUP}"

exit 0
