name: Build macOS pkg Installer

on:
  workflow_dispatch:
    inputs:
      incoming_ref:
        description: >
          The ref from Cantera/cantera to be built. Can be a tag, commit hash,
          or branch name.
        required: true
        default: "main"

env:
  MW_HEADERS_DIR: ${{ github.workspace }}/mw_headers
  MACOSX_DEPLOYMENT_TARGET: "10.11"
  PKG_DIR: ${{ github.workspace }}

jobs:
  build-intel:
    name: Build Intel-based package
    runs-on: macos-10.15
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
      - name: Checkout Cantera repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          repository: Cantera/cantera
          path: cantera
          ref: ${{ github.event.inputs.incoming_ref }}
      - name: Get the MATLAB headers
        run: git clone https://cantera:${GIT_PW}@cantera.org/mw_headers.git "${MW_HEADERS_DIR}"
        env:
          GIT_PW: ${{ secrets.GIT_PW }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: |
          python -m pip install -U pip setuptools
          python -m pip install scons
      - name: Install Brew dependencies
        run: brew install boost
      - name: Install Packages
        run: sudo /usr/sbin/installer -pkg Packages.pkg -target /
      - name: Build Cantera
        working-directory: cantera
        run: |
          echo "matlab_path='${MW_HEADERS_DIR}'" >> cantera.conf
          echo "f90_interface='n'" >> cantera.conf
          echo "system_sundials='n'" >> cantera.conf
          echo "debug='n'" >> cantera.conf
          echo "python_package='none'" >> cantera.conf
          echo "prefix='${PKG_DIR}'" >> cantera.conf
          echo "layout='compact'" >> cantera.conf
          python3 `which scons` build -j2 VERBOSE=y
      - name: Test Cantera
        working-directory: cantera
        run: python3 `which scons` test-general test-thermo test-kinetics test-transport
      - name: Install Cantera
        working-directory: cantera
        run: python3 `which scons` install
      - name: Package Cantera
        run: /usr/local/bin/packagesbuild ./cantera-matlab-interface.pkgproj
      - name: Upload the pkg artifact
        uses: actions/upload-artifact@v2
        with:
          path: build/*.pkg
          name: intel

  build-arm:
    name: Build ARM-based package
    runs-on: macos-10.15
    env:
      SDKROOT: "macosx11.0"
      _PYTHON_HOST_PLATFORM: "macosx-11.0-arm64"
      ARCHFLAGS: "-arch arm64"
      DEVELOPER_DIR: "/Applications/Xcode_12.2.app/Contents/Developer"
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
      - name: Checkout Cantera repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          repository: Cantera/cantera
          path: cantera
          ref: ${{ github.event.inputs.incoming_ref }}
      - name: Get the MATLAB headers
        run: git clone https://cantera:${GIT_PW}@cantera.org/mw_headers.git "${MW_HEADERS_DIR}"
        env:
          GIT_PW: ${{ secrets.GIT_PW }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: |
          python -m pip install -U pip setuptools
          python -m pip install scons
      - name: Install Brew dependencies
        run: brew install boost
      - name: Install Packages
        run: sudo /usr/sbin/installer -pkg Packages.pkg -target /
      - name: Build Cantera
        working-directory: cantera
        run: |
          echo "matlab_path='${MW_HEADERS_DIR}'" >> cantera.conf
          echo "f90_interface='n'" >> cantera.conf
          echo "system_sundials='n'" >> cantera.conf
          echo "debug='n'" >> cantera.conf
          echo "python_package='none'" >> cantera.conf
          echo "prefix='${PKG_DIR}'" >> cantera.conf
          echo "layout='compact'" >> cantera.conf
          python3 `which scons` build -j2 VERBOSE=y env_vars=all
      # Testing won't work until native Apple Silicon builders
      # are available
      # - name: Test Cantera
      #   working-directory: cantera
      #   run: python3 `which scons` test-general test-thermo test-kinetics test-transport
      - name: Install Cantera
        working-directory: cantera
        run: python3 `which scons` install
      - name: Package Cantera
        run: /usr/local/bin/packagesbuild ./cantera-matlab-interface.pkgproj
      - name: Upload the pkg artifact
        uses: actions/upload-artifact@v2
        with:
          path: build/*.pkg
          name: arm
